### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by xPh03n1x** [eusonlito/Sublime-Text-ChatGPT#1]
I just installed the plugin in Sublime Text 3, added the API key and went through the other settings. On the first attempt to get a generated code with the prompt `php hello world` I just got an error for Not Found.

I enabled debug and here's the output, albeit not really useful:

```
settings {'max_tokens': 4096, 'timeout': 20, 'api_key': 'sk-***REDACTED***', 'debug': True, 'temperature': 0.5, 'model': 'gpt-3.5-turbo'}
show_input_done[input_string] php hello world
request[data] b'{"prompt": "php hello world", "max_tokens": 4096, "model": "gpt-3.5-turbo", "temperature": 0.5}'
request[text] # Error: HTTP Error 404: Not Found #
```

P.S.:
Changing the model to `text-davinci-003` results in `400 Bad Request`:
```
settings {'max_tokens': 4096, 'timeout': 20, 'api_key': 'sk-***REDACTED***', 'debug': True, 'temperature': 0.5, 'model': 'text-davinci-003'}
show_input_done[input_string] php hello world
request[data] b'{"prompt": "php hello world", "max_tokens": 4096, "model": "text-davinci-003", "temperature": 0.5}'
request[text] # Error: HTTP Error 400: Bad Request #
```

**Comment by eusonlito** [comment]
I have this settings working fine currently:

```json
{
    "api_key": "",
    "model": "text-davinci-003",
    "temperature": 0.5,
    "max_tokens": 1024,
    "timeout": 30,
    "debug": true
}
```

**Comment by xPh03n1x** [comment]
It appears that the `max_tokens` variable is somehow messing this up.

Changing `max_tokens` to `1024` and using `text-davinci-003` model works!

**Comment by STEMP007** [comment]
Is there an option to use a newer version for the model? there is mentionned "// The default model is the used by chatgpt web tool"  does this means even when the model is indicated "text-davinci-003" the default model by chatgpt is used? When i input another version, i also got the error. 404 not found.

**Comment by STEMP007** [comment]
Is there a possibility to swith to a more recent model? like gpt-3.5-turbo? There is always an error when i try to use a more recent model. thanks in advance.
