### ISSUE TITLE
Enter/Return adds a new line

### ISSUE THREAD

**Issue by milosmns** [eusonlito/Sublime-Text-ChatGPT#2]
Hey, I'm struggling to get it to work… I wonder what I'm doing wrong.

I've added the API key. So basically I type a question in the input field, hit enter/return… but nothing happens (the field goes blank). 
Then I realize it actually adds a new line (`\n`)! Oops… I tried CMD+Enter, Opt+Enter, Ctrl+Enter, all 3 add a new line 😢 

Help me out please.

**Comment by eusonlito** [comment]
Can you try to test it with the ST console visible? (View > Show Console)

**Comment by milosmns** [comment]
Thanks for the fast reply — I was about to come to write back; I forgot that I did some rebinding and hooked enter/return to behave somewhat differently.

There's no issue, I just didn't open Sublime Text for a while to remember my old key bindings. Thanks again!
